version: 0.0
os: linux
hooks:
  ApplicationStop:
    - location: codedeploy/application-stop.sh
      timeout: 300
      runas: root

  BeforeInstall:
    - location: codedeploy/before-install.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: codedeploy/after-install.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: codedeploy/application-start.sh
      timeout: 300
      runas: root

  ValidateService:
    - location: codedeploy/validate-service.sh
      timeout: 300
  
