version: 0.0
os: linux
hooks:
  ApplicationStop:
    - location: codedeploy/1_application-stop.sh
      timeout: 300
      runas: root

  BeforeInstall:
    - location: codedeploy/2_before-install.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: codedeploy/3_after-install.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: codedeploy/4_application-start.sh
      timeout: 300
      runas: root

  ValidateService:
    - location: codedeploy/5_validate-service.sh
      timeout: 300
  
