version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8

  build:
    commands:
      - cp examples/env.LOCAL /etc/default/env.LOCAL
      - pip3 install -r requirements.txt
      - python3 manage.py migrate
      - python3 manage.py test

artifacts:
  files:
    - "**/*"
