version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7

  build:
    commands:
      - pip3 install -r requirements.txt
      - python3 manage.py migrate
      - python3 manage.py test

artifacts:
  files:
    - "**/*"
