# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-12-11 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
