# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-12-11 22:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactmanager', '0002_webpage_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webpage',
            name='description',
        ),
    ]
