# Generated by Django 2.2.12 on 2020-12-11 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contactmanager', '0003_remove_webpage_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessrecord',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contactmanager.WebPage'),
        ),
    ]
