# Generated by Django 3.1.4 on 2021-01-03 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contactmanager', '0004_auto_20201211_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webpages', to='contactmanager.topic'),
        ),
    ]
