# Generated by Django 3.1.4 on 2021-01-03 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactmanager', '0005_auto_20210103_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webpage',
            old_name='url',
            new_name='webpage_url',
        ),
    ]
